### ISSUE TITLE
Segment default 段错误，import pdbfixer，and from stimtk import app

### ISSUE THREAD

**Issue by zhangyichen534** [google-deepmind/alphafold#1015]
在导入这两个包的时候发生段错误，具体表现如下：
root: python
Python 3.8.19 (default, Mar 20 2024, 19:58:24) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdbfixer
段错误 (核心已转储)

刚开始执行的时候没什么问题，也成功跑出来了输出文件，然后跑了两次之后就开始脚本不运行直接退出，经过定位后是这两个包的问题。

尝试过，卸载重装，重新安装python，以及conda环境，都没什么用。

gdb调试定位后报错情况如下：
GNU gdb (Ubuntu 10.2-0ubuntu1~18.04~2) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
"0x7fff783f5880s": not in executable format: file format not recognized
[New LWP 11764]
Core was generated by `python testpdffixer.py'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f14448252fb in ?? ()
(gdb) bt
#0  0x00007f14448252fb in ?? ()
#1  0x00007f143ede70c8 in ?? ()
#2  0x000000005f6f1c70 in ?? ()
#3  0x00000000fb000000 in ?? ()
#4  0x0000000000000001 in ?? ()
#5  0x000000000000046c in ?? ()
#6  0x00007ffe5f6f1b1c in ?? ()
#7  0x0000000000000000 in ?? ()

不知道怎么解决这个问题了。

**Comment by zhangyichen534** [comment]
有没有大神帮忙看一下，应该怎么办
