### ISSUE TITLE
ModuleNotFoundError: No module named 'tree'

### ISSUE THREAD

**Issue by adokhugi** [google-deepmind/alphafold#1047]
Microsoft Windows [Version 10.0.22631.4460]
(c) Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Acer\source\repos\alphafold>python run_alphafold_test.py
Traceback (most recent call last):
  File "C:\Users\Acer\source\repos\alphafold\run_alphafold_test.py", line 22, in <module>
    import run_alphafold
  File "C:\Users\Acer\source\repos\alphafold\run_alphafold.py", line 31, in <module>
    from alphafold.common import protein
  File "C:\Users\Acer\source\repos\alphafold\alphafold\common\protein.py", line 23, in <module>
    from alphafold.common import residue_constants
  File "C:\Users\Acer\source\repos\alphafold\alphafold\common\residue_constants.py", line 23, in <module>
    import tree
ModuleNotFoundError: No module named 'tree'

C:\Users\Acer\source\repos\alphafold>

I tried pip install dm-tree, it did not help.

**Comment by praharsh777** [comment]
Hi! I’ve submitted a pull request that resolves this issue: #1080 
It includes a fix for the `tree` module error and also addresses `pdbfixer` installation on Windows. All tests passed, and a Windows-specific installation guide has been added to the README.
Would appreciate it if someone could take a look! 🙏
