### ISSUE TITLE
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.47/containers/create: Not Found ("No such image: alphafold:latest")

### ISSUE THREAD

**Issue by kn301BE** [google-deepmind/alphafold#1053]
Hi all:
When I try to run python3 docker/run_docker.py --fasta_paths=gfp.fasta --max_template_date=2024-12-30 --data_dir=/media/1E8E7BAA8E7B795B/database/ --db_preset=reduced_dbs --output_dir=/home/CD47/
I got the following issues:
I1231 17:50:01.220709 129183842236224 run_docker.py:116] Mounting /home/gaon/alphafold -> /mnt/fasta_path_0
I1231 17:50:01.221176 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/uniref90 -> /mnt/uniref90_database_path
I1231 17:50:01.221523 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/mgnify -> /mnt/mgnify_database_path
I1231 17:50:01.221757 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database -> /mnt/data_dir
I1231 17:50:01.222091 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I1231 17:50:01.222338 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1231 17:50:01.222602 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/pdb70 -> /mnt/pdb70_database_path
I1231 17:50:01.222913 129183842236224 run_docker.py:116] Mounting /media/gaon/1E8E7BAA8E7B795B/database/small_bfd -> /mnt/small_bfd_database_path
Traceback (most recent call last):
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.47/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.47/containers/create: Not Found ("No such image: alphafold:latest")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.47/images/create?tag=latest&fromImage=alphafold

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaon/alphafold/docker/run_docker.py", line 267, in <module>
    app.run(main)
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/gaon/alphafold/docker/run_docker.py", line 237, in main
    container = client.containers.run(
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/models/containers.py", line 814, in run
    self.client.images.pull(image, platform=platform)
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/models/images.py", line 446, in pull
    pull_log = self.client.api.pull(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/image.py", line 430, in pull
    self._raise_for_status(response)
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gaon/miniconda3/lib/python3.11/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.47/images/create?tag=latest&fromImage=alphafold: Internal Server Error ("Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)")

I used docker images
And this is my output:
'''
REPOSITORY    TAG                       IMAGE ID       CREATED          SIZE
alphafold     latest                    5ea074d4fce3   38 minutes ago   11.4GB
nvidia/cuda   12.2.0-base-ubuntu22.04   00d989b22f26   13 months ago    239MB
hello-world   latest                    d2c94e258dcb   20 months ago    13.3kB
’‘’
But when I check python I found that I could not see the images in python which looks like that ：
[<Image: ''>, <Image: 'hello-world:latest'>, <Image: 'ubuntu:xenial'>]
Any help would be appreciated.

**Comment by kushvinth** [comment]
The error isn’t with AlphaFold itself — it’s usually caused by a missing or mismatched alphafold:latest image tag, or Docker socket misconfiguration. Rebuilding or retagging the image almost always resolves it.


```bash
bash docker/build.sh
# or
docker tag <image-id> alphafold:latest
```

Also ensure you’re on the correct Docker context (docker context use default). Re-run the command afterward — this should resolve the issue.
