### ISSUE TITLE
Issue with pdb70 "ValueError: Could not find HHsearch database."

### ISSUE THREAD

**Issue by northNomad** [google-deepmind/alphafold#847]
Hi everyone,

I'm trying to troubleshoot an error that's previously been reported at #518 
The error message looks something like **ValueError: Could not find HHsearch database**. 
I think the script cannot access the pdb70 database and it's apparently a permission issue for most of the folks on the thread.

But fixing the permission issue does not solve the error in my case.
I'm running AF2 as a module on my institution's cluster.
To address the permission issue, I copied the pdb70 directory to my own directory and chmod 777 all the files.

Like this:
```
(base) [alexliu@node91 pdb70]$ ls -l
total 70673512
-rwxrwxrwx 1 alexliu chanlab         410 Oct 20 17:44 md5sum
-rwxrwxrwx 1 alexliu chanlab 56554823611 Oct 20 17:48 pdb70_a3m.ffdata
-rwxrwxrwx 1 alexliu chanlab     2049264 Oct 20 17:48 pdb70_a3m.ffindex
-rwxrwxrwx 1 alexliu chanlab     6967926 Oct 20 17:44 pdb70_clu.tsv
-rwxrwxrwx 1 alexliu chanlab    22338334 Oct 20 17:43 pdb70_cs219.ffdata
-rwxrwxrwx 1 alexliu chanlab     1562700 Oct 20 17:44 pdb70_cs219.ffindex
-rwxrwxrwx 1 alexliu chanlab  3485614545 Oct 20 17:44 pdb70_hhm.ffdata
-rwxrwxrwx 1 alexliu chanlab     1884124 Oct 20 17:43 pdb70_hhm.ffindex
-rwxrwxrwx 1 alexliu chanlab    20263781 Oct 20 17:43 pdb_filter.dat
```

Then I specify the pdb70 directory path to the one which I have permission over.
The script looks like:
```
#!/bin/bash
#SBATCH -t 72:00:00
#SBATCH -p gpu
#SBATCH -A chanlab_gpu
#SBATCH --mem 150G
#SBATCH -c 1

module load alphafold/2.3.1

python /cluster/tools/software/centos7/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py \
        --fasta_paths=~/P42212.fasta \
        --max_template_date=2023-10-19 \
        --model_preset=monomer \
        --use_gpu_relax \
        --db_preset=full_dbs \
        --data_dir=/cluster/tools/data/commondata/alphafold \
        --output_dir=~/alphafold_test \
        --uniref90_database_path=/cluster/tools/data/commondata/alphafold/uniref90 \
        --mgnify_database_path=/cluster/tools/data/commondata/alphafold/mgnify \
        --template_mmcif_dir=/cluster/tools/data/commondata/alphafold/pdb_mmcif/mmcif_files \
        --obsolete_pdbs_path=/cluster/tools/data/commondata/alphafold/pdb_mmcif/obsolete.dat \
        --bfd_database_path=/cluster/tools/data/commondata/alphafold/bfd \
        --uniref30_database_path=/cluster/tools/data/commondata/alphafold/uniref30 \
        --pdb70_database_path=/cluster/projects/chanlab/pdb70
```
But I am still getting the same error even with permission to access the files.
```
(base) [alexliu@node52 alphafold_test]$ cat slurm-10409121.out
The databases of alphafold are at $alphafold_data.
$alphafold_home is set to /cluster/tools/software/centos7/alphafold/2.3.1.
E1025 16:12:36.010123 139968497416000 hhsearch.py:56] Could not find HHsearch database /cluster/projects/chanlab/pdb70
Traceback (most recent call last):
  File "/cluster/tools/software/centos7/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py", line 432, in <module>
    app.run(main)
  File "/cluster/tools/software/centos7/alphafold/2.3.1/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/cluster/tools/software/centos7/alphafold/2.3.1/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/cluster/tools/software/centos7/alphafold/2.3.1/alphafold-2.3.1/run_alphafold.py", line 337, in main
    template_searcher = hhsearch.HHSearch(
  File "/cluster/tools/software/centos7/alphafold/2.3.1/alphafold-2.3.1/alphafold/data/tools/hhsearch.py", line 57, in __init__
    raise ValueError(f'Could not find HHsearch database {database_path}')
ValueError: Could not find HHsearch database /cluster/projects/chanlab/pdb70
```

Can anyone let me know if I'm approaching this correctly?

Many thanks in advance.
A.L.

**Comment by Augustin-Zidek** [comment]
The HHSearch PDB70 "path" has to include also the common prefix for all of the db files in the directory. I.e. in your case the path should be `/cluster/projects/chanlab/pdb70/pdb70`.

**Comment by northNomad** [comment]
Hi @Augustin-Zidek , that fixed it!! Thank you so much!
