### ISSUE TITLE
ERROR: Could find neither hhm_db nor a3m_db! 

### ISSUE THREAD

**Issue by loggy01** [google-deepmind/alphafold#858]
Hi all,

My download directory matches that currently specified on the AlphaFold read me but during runtime I get the following error:

```
stderr:


I1115 22:08:36.661796 23135168587584 utils.py:40] Finished hmmbuild query in 0.992 seconds
I1115 22:08:36.665484 23135168587584 hmmsearch.py:103] Launching sub-process ['/sw-eb/software/HMMER/3.3.2-gompi-2022a/bin/hmmsearch', '--noali', '--cpu', '8', '--F1', '0.1', '--F2', '0.1', '--F3', '0.1', '--incE', '100', '-E', '100', '--domE', '100', '--incdomE', '100', '-A', '/var/tmp/pbs.8472060.pbs/tmpwgs4p_y9/output.sto', '/var/tmp/pbs.8472060.pbs/tmpwgs4p_y9/query.hmm', '/rds/easybuild/data/alphafold/2.3.0/pdb_seqres/pdb_seqres.txt']
I1115 22:08:36.735591 23135168587584 utils.py:36] Started hmmsearch (pdb_seqres.txt) query
I1115 22:08:46.050867 23135168587584 utils.py:40] Finished hmmsearch (pdb_seqres.txt) query in 9.315 seconds
I1115 22:08:47.593513 23135168587584 hhblits.py:128] Launching subprocess "/sw-eb/software/HH-suite/3.3.0-gompi-2022a/bin/hhblits -i /var/tmp/pbs.8472060.pbs/tmpbu0bk2ou.fasta -cpu 4 -oa3m /var/tmp/pbs.8472060.pbs/tmpawem0edw/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /rds/easybuild/data/alphafold/2.3.0/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /rds/easybuild/data/alphafold/2.3.0/uniref30/UniRef30_2021_03"
I1115 22:08:47.727102 23135168587584 utils.py:36] Started HHblits query
I1115 22:08:56.156595 23135168587584 utils.py:40] Finished HHblits query in 8.429 seconds
E1115 22:08:56.157379 23135168587584 hhblits.py:138] HHblits failed. HHblits stderr begin:
E1115 22:08:56.157752 23135168587584 hhblits.py:141] - 22:08:56.114 ERROR: Could find neither hhm_db nor a3m_db!
E1115 22:08:56.157804 23135168587584 hhblits.py:142] HHblits stderr end
Traceback (most recent call last):
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 288, in <module>
    app.run(main)
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 280, in main
    create_and_save_monomer_objects(curr_monomer, pipeline,
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 215, in create_and_save_monomer_objects
    m.make_features(
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 119, in make_features
    self.feature_dict = pipeline.process(
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 215, in process
    hhblits_bfd_uniref_result = run_msa_tool(
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 96, in run_msa_tool
    result = msa_runner.query(input_fasta_path)[0]
  File "/rds/general/user/al519/home/anaconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/tools/hhblits.py", line 143, in query
    raise RuntimeError('HHblits failed\nstdout:\n%s\n\nstderr:\n%s\n' % (
RuntimeError: HHblits failed
stdout:


stderr:
- 22:08:56.114 ERROR: Could find neither hhm_db nor a3m_db!
```
Is it possible that this just a permissions issue (maybe to do with uniref30) or could it be something else?

Best wishes,
Aaron

**Comment by loggy01** [comment]
For anyone wondering, here is my database directory (necessary files within):

.
├── bfd
├── mgnify
├── params
├── pdb70
├── pdb_mmcif
│ └── mmcif_files
├── pdb_seqres
├── uniprot
├── uniref30
└── uniref90

**Comment by loggy01** [comment]
The issue was permission-based. Make sure the files in your AF2 database are readable by all users.
