### ISSUE TITLE
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/containers/ee2565cd6294bdf23537e9fb81814d89cb240f8c02b23f24a0926e3c66b44aea/start: Internal Server Error ("could not select device driver "nvidia" with capabilities: [[gpu]]")

### ISSUE THREAD

**Issue by khanhtavish** [google-deepmind/alphafold#886]
Had successfully built GPU environment and the alphafold docker image (AlphaFold V2.3.2) on the Centos8.

<img width="1317" alt="image" src="https://github.com/google-deepmind/alphafold/assets/99472745/1af1fe86-ea35-463e-a606-4bf6dc0f80ab">

**When I run the alphafold by the following command:**
python3 docker/run_docker.py --fasta_paths=/myshare/khanh/projects/alphafold/1cxz.fasta --max_template_date=2022-01-01 --data_dir=/myshare/database/alphafold --output_dir=/myshare/khanh/projects/alphafold/

**I got the following **error:****
I0118 09:22:00.403837 140362355152704 run_docker.py:113] Mounting /myshare/khanh/projects/alphafold -> /mnt/fasta_path_0
I0118 09:22:00.404139 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/uniref90 -> /mnt/uniref90_database_path
I0118 09:22:00.404336 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/mgnify -> /mnt/mgnify_database_path
I0118 09:22:00.404402 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold -> /mnt/data_dir
I0118 09:22:00.404542 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0118 09:22:00.404651 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0118 09:22:00.404766 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/pdb70 -> /mnt/pdb70_database_path
I0118 09:22:00.404883 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/uniref30 -> /mnt/uniref30_database_path
I0118 09:22:00.404992 140362355152704 run_docker.py:113] Mounting /myshare/database/alphafold/bfd -> /mnt/bfd_database_path
Traceback (most recent call last):
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.43/containers/ee2565cd6294bdf23537e9fb81814d89cb240f8c02b23f24a0926e3c66b44aea/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "docker/run_docker.py", line 264, in <module>
    app.run(main)
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 234, in main
    container = client.containers.run(
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/models/containers.py", line 880, in run
    container.start()
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/models/containers.py", line 417, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/container.py", line 1135, in start
    self._raise_for_status(res)
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/api/client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/khanh/biosoft/miniconda3/envs/alphafold/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.43/containers/ee2565cd6294bdf23537e9fb81814d89cb240f8c02b23f24a0926e3c66b44aea/start: Internal Server Error ("could not select device driver "nvidia" with capabilities: [[gpu]]")

**Comment by wenz1xv** [comment]
Installing the NVIDIA Container Toolkit may solve this problem.
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

**Comment by sherryliu987** [comment]
If you're struggling to install AlphaFold locally, feel free to try https://www.tamarind.bio/alphafold, a website which offers a no-code interface for bioinformatics tools including protein structure with AlphaFold for free.
