### ISSUE TITLE
` HHSearch failed` with no `stdout` or `stderr` output

### ISSUE THREAD

**Issue by GentleInfant** [google-deepmind/alphafold#897]
Running a job is failing with

```
I0214 13:38:24.695471 140207840163648 utils.py:36] Started HHsearch query
I0214 13:38:24.777242 140207840163648 utils.py:40] Finished HHsearch query in 0.082 seconds
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 468, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 443, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 196, in predict_structure
    feature_dict = data_pipeline.process(
  File "/app/alphafold/alphafold/data/pipeline.py", line 188, in process
    pdb_templates_result = self.template_searcher.query(uniref90_msa_as_a3m)
  File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 94, in query
    raise RuntimeError(
RuntimeError: HHSearch failed:
stdout:


stderr:


```

I'm using the singularity image but the developer on git says it's an issue with alphafold he can't fix. I'm pretty sure I tried adding the `-DHAVEX_AVX2=1` but it didn't help. (feel free to suggest I try again if you think that's what it is - I've tried a lot of things!). I don't believe it's ever worked on this machine (I'm not the only one trying to get it to work).

I'm running the image as a slurm job with 64G memory (I saw another ticket that mentioned they hadn't assigned enough memory but 64G was the amount of memory on a bare metal install on a different machine that has alphafold working).

**Comment by GentleInfant** [comment]
Nope, no solutions have been forthcoming :/

The way I tried to do it was to edit the `Singularity.def` file and according to the instructions [here](https://github.com/soedinglab/hh-suite/issues/282) add it to the `CMAKE` line, for me that's line 48: `&& cmake -DCMAKE_INSTALL_PREFIX=/opt/hhsuite .. \`

**Comment by wtroy2** [comment]
I am still having this problem. Has anyone found a solution?

**Comment by gioodm** [comment]
Not sure if this is a viable solutions for you, but my workaround was to just not use HHsearch by removing the —template option

**Comment by MrDotOne** [comment]
Has anyone found a solution to this problem? I know this issue is from 2024 but i am encountering the same issue using the singularity script and the 2.3.2 docker image. I tried removing the --template options but the singularity script doesnt like that and says it is required. I also tried a template date of 1001-01-01 and that failed to work as well.
