### ISSUE TITLE
ValueError: Could not find CIFs

### ISSUE THREAD

**Issue by leonhardt913** [google-deepmind/alphafold#909]
I have been setting up the alphafold2 along with Docker.  When I came to step 8 for test, I put the command in .sh file and run, but the following errors occurs:

```
~/bin/alphafold$ cat run_alphafold.sh
python3 docker/run_docker.py \
  --fasta_paths=fastafiles/test_protein.fasta \
  --max_template_date=2023-12-30 \
  --data_dir=/data/disk4/alphafoldDB \
  --output_dir=~/project/3-alphafold2-output
```

```
~/bin/alphafold $ sh run_alphafold.sh
I0313 20:59:48.014863 139881018193024 run_docker.py:116] Mounting /home/wuqy/bin/alphafold/fastafiles -&gt; /mnt/fasta_path_0
I0313 20:59:48.223854 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/uniref90 -&gt; /mnt/uniref90_database_path
I0313 20:59:48.429889 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/mgnify -&gt; /mnt/mgnify_database_path
I0313 20:59:48.430127 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB -&gt; /mnt/data_dir
I0313 20:59:48.432076 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/pdb_mmcif -&gt; /mnt/template_mmcif_dir
I0313 20:59:48.433026 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/pdb_mmcif -&gt; /mnt/obsolete_pdbs_path
I0313 20:59:48.434590 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/pdb70 -&gt; /mnt/pdb70_database_path
I0313 20:59:48.436120 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/uniref30 -&gt; /mnt/uniref30_database_path
I0313 20:59:48.437566 139881018193024 run_docker.py:116] Mounting /data/disk4/alphafoldDB/bfd -&gt; /mnt/bfd_database_path
I0313 20:59:51.911179 139881018193024 run_docker.py:258] E0313 12:59:51.910264 139938819991360 templates.py:838] Could not find CIFs in /mnt/template_mmcif_dir/mmcif_files

I0313 20:59:51.911416 139881018193024 run_docker.py:258] Traceback (most recent call last):
I0313 20:59:51.911603 139881018193024 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 570, in &lt;module&gt;
I0313 20:59:51.911774 139881018193024 run_docker.py:258] app.run(main)
I0313 20:59:51.911936 139881018193024 run_docker.py:258] File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 312, in run
I0313 20:59:51.912092 139881018193024 run_docker.py:258] _run_main(main, args)
I0313 20:59:51.912245 139881018193024 run_docker.py:258] File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 258, in _run_main
I0313 20:59:51.912397 139881018193024 run_docker.py:258] sys.exit(main(argv))
I0313 20:59:51.912575 139881018193024 run_docker.py:258] File "/app/alphafold/run_alphafold.py", line 478, in main
I0313 20:59:51.912730 139881018193024 run_docker.py:258] template_featurizer = templates.HhsearchHitFeaturizer(
I0313 20:59:51.912881 139881018193024 run_docker.py:258] File "/app/alphafold/alphafold/data/templates.py", line 839, in __init__
I0313 20:59:51.913031 139881018193024 run_docker.py:258] raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
I0313 20:59:51.913180 139881018193024 run_docker.py:258] ValueError: Could not find CIFs in /mnt/template_mmcif_dir/mmcif_files
```

I have also reviewed issue #160 about the Singularity approach, but I am not familiar with it. Is there a feasible solution to address this issue based on the current Docker configuration?

**Comment by Ruibin-Liu** [comment]
Does anyone have found a solution?

**Comment by Ruibin-Liu** [comment]
For my case, the problem is that the CIF files in the pdb_mmcif/raw directories are not 'flatterned' because one gz file might be damaged. My solution was just to download the mmcif dataset again. Double check that there is a pdb_mmcif/mmcif_files directory before running the docker script.

**Comment by leonhardt913** [comment]
@Ruibin-Liu Thank you. I will try re-downloading the CIF files again. But it is very unstable to download this part and i believe the files might be damaged during the occasionally disconnect

**Comment by MauriAndresMU1313** [comment]
Hi everyone. I have the same question: Should I unzip the .gz files? 
Thank you!

**Comment by AravindKurapati** [comment]
The `.gz` files should not be unzipped by hand, and the error is usually an interrupted download.

`scripts/download_pdb_mmcif.sh` does three things in sequence:

1. rsyncs into `pdb_mmcif/raw/`, which is nested by two-character subdirectory and gzipped
2. gunzips everything in `raw/` in place
3. flattens: moves every `.cif` out of the `raw/` subdirectories into `pdb_mmcif/mmcif_files/`, then deletes the now-empty directories

So the finished layout is a flat `pdb_mmcif/mmcif_files/` of uncompressed `.cif` files, an empty or absent `raw/`, and `obsolete.dat` in `pdb_mmcif/`. AlphaFold reads `mmcif_files/`, which is why the error names that path.

If the script is interrupted during step 1 or 2 (rsync is the long one), you are left with a populated `raw/` and no `mmcif_files/`, which raises exactly this ValueError. Nothing is corrupt in that case.

To tell which state you are in:

```
ls /path/to/pdb_mmcif/mmcif_files | wc -l    # expect ~200k files
find /path/to/pdb_mmcif/raw -name "*.gz" | head    # expect no output
```

The fix is to re-run the same script and let it finish. rsync syncs against what is already there rather than refetching everything, so a resumed run is much shorter than the first one.

```
./scripts/download_pdb_mmcif.sh /path/to/download_dir
```

If aria2c or rsync are not installed on the host, the script can be run inside the AlphaFold image instead:

```
docker run --rm --entrypoint bash \
  -v /path/to/download_dir:/data \
  alphafold /app/alphafold/scripts/download_pdb_mmcif.sh /data
```

For anyone hitting this on a long download over SSH: run it under `nohup` or `tmux`, since the session dropping is what interrupts it in the first place.
