### ISSUE TITLE
ValueError: Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by rytakahashi** [google-deepmind/alphafold#923]
```
...
I0404 21:01:29.229502 140648689870656 amber_minimize.py:69] Restraining 478 / 979 particles.
I0404 21:01:29.413306 140648689870656 amber_minimize.py:418] Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
I0404 21:01:29.493218 140648689870656 amber_minimize.py:408] Minimizing protein, attempt 100 of 100.
I0404 21:01:29.597103 140648689870656 amber_minimize.py:69] Restraining 478 / 979 particles.
I0404 21:01:29.781777 140648689870656 amber_minimize.py:418] Unit "kilocalorie/mole" is not compatible with Unit "kilojoule/(nanometer*mole)".
Traceback (most recent call last):
  File "/home/af2/alphafold_2.3.2/run_alphafold.py", line 570, in <module>
    app.run(main)
  File "/home/af2/miniconda3/envs/af_2.3.2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/af2/miniconda3/envs/af_2.3.2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/af2/alphafold_2.3.2/run_alphafold.py", line 543, in main
    predict_structure(
  File "/home/af2/alphafold_2.3.2/run_alphafold.py", line 361, in predict_structure
    relaxed_pdb_str, _, violations = amber_relaxer.process(
  File "/home/af2/alphafold_2.3.2/alphafold/relax/relax.py", line 62, in process
    out = amber_minimize.run_pipeline(
  File "/home/af2/alphafold_2.3.2/alphafold/relax/amber_minimize.py", line 476, in run_pipeline
    ret = _run_one_iteration(
  File "/home/af2/alphafold_2.3.2/alphafold/relax/amber_minimize.py", line 420, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.
```
what could be a solution for this in alphafold 2.3.2 ? 
Thanks

**Comment by dingquanyu** [comment]
Hi all,

I encountered the same problem. complaining about the unit. I'm using openmm 8.1.1 and downgrading to 7.7.0 will crash the pdbfixer imports

**Comment by uniquelemon** [comment]
> Hi all,
> 
> I encountered the same problem. complaining about the unit. I'm using openmm 8.1.1 and downgrading to 7.7.0 will crash the pdbfixer imports

Check the version of pdbfixer. Different versions of openmm require different versions of pdbfixer. 

It is indeed the openmm version that causes this problem. The openmm8.1.1 installed had the same error, but reinstalling openmm8.0.0 can run normally.

**Comment by rytakahashi** [comment]
As the above, down grate openmm, I was able to solve the issue as well.

Many thanks,

**Comment by catsled** [comment]
openmm==8.0.0 and pdbfixer==1.9 is ok
